// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package types

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusOk HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatusChecksDb.
const (
	ReadinessStatusChecksDbDown ReadinessStatusChecksDb = "down"
	ReadinessStatusChecksDbOk   ReadinessStatusChecksDb = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessStatusChecksDb enum.
func (e ReadinessStatusChecksDb) Valid() bool {
	switch e {
	case ReadinessStatusChecksDbDown:
		return true
	case ReadinessStatusChecksDbOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatusStatus.
const (
	Degraded ReadinessStatusStatus = "degraded"
	Ok       ReadinessStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessStatusStatus enum.
func (e ReadinessStatusStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// HealthStatus Liveness response indicating the process is up and serving requests.
type HealthStatus struct {
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// ReadinessStatus Readiness response reporting aggregate status and per-dependency check results.
type ReadinessStatus struct {
	Checks struct {
		Db ReadinessStatusChecksDb `json:"db"`
	} `json:"checks"`
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusChecksDb defines model for ReadinessStatus.Checks.Db.
type ReadinessStatusChecksDb string

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string
