// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCrawl = `-- name: CreateCrawl :one
INSERT INTO crawls (seed_url, max_depth, max_pages, status)
VALUES ($1, $2, $3, 'queued')
RETURNING id, seed_url, max_depth, max_pages, status, created_at, updated_at
`

type CreateCrawlParams struct {
	SeedUrl  string
	MaxDepth int32
	MaxPages int32
}

func (q *Queries) CreateCrawl(ctx context.Context, arg CreateCrawlParams) (Crawl, error) {
	row := q.db.QueryRow(ctx, createCrawl, arg.SeedUrl, arg.MaxDepth, arg.MaxPages)
	var i Crawl
	err := row.Scan(
		&i.ID,
		&i.SeedUrl,
		&i.MaxDepth,
		&i.MaxPages,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCrawlByID = `-- name: GetCrawlByID :one
SELECT id, seed_url, max_depth, max_pages, status, created_at, updated_at
FROM crawls
WHERE id = $1
`

func (q *Queries) GetCrawlByID(ctx context.Context, id pgtype.UUID) (Crawl, error) {
	row := q.db.QueryRow(ctx, getCrawlByID, id)
	var i Crawl
	err := row.Scan(
		&i.ID,
		&i.SeedUrl,
		&i.MaxDepth,
		&i.MaxPages,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCrawlsAfterCursor = `-- name: ListCrawlsAfterCursor :many
SELECT id, seed_url, max_depth, max_pages, status, created_at, updated_at
FROM crawls
WHERE (created_at, id) < ($1::timestamptz, $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListCrawlsAfterCursorParams struct {
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageLimit       int32
}

func (q *Queries) ListCrawlsAfterCursor(ctx context.Context, arg ListCrawlsAfterCursorParams) ([]Crawl, error) {
	rows, err := q.db.Query(ctx, listCrawlsAfterCursor, arg.CursorCreatedAt, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crawl
	for rows.Next() {
		var i Crawl
		if err := rows.Scan(
			&i.ID,
			&i.SeedUrl,
			&i.MaxDepth,
			&i.MaxPages,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrawlsFirstPage = `-- name: ListCrawlsFirstPage :many
SELECT id, seed_url, max_depth, max_pages, status, created_at, updated_at
FROM crawls
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListCrawlsFirstPage(ctx context.Context, limit int32) ([]Crawl, error) {
	rows, err := q.db.Query(ctx, listCrawlsFirstPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crawl
	for rows.Next() {
		var i Crawl
		if err := rows.Scan(
			&i.ID,
			&i.SeedUrl,
			&i.MaxDepth,
			&i.MaxPages,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
